---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
  - >
    ansible-playbook -i inventory playbook.yml --sudo
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


#script:
  # Basic role syntax check
#  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

#script:
#  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
#  - 'cd rolespec ; bin/rolespec -r https://github.com/debops/test-suite'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/